steps:
- name: 'gcr.io/cloud-builders/dotnet'
  args: ['publish', '-c', 'Release']
  dir: './IgniteCLI'
  timeout: 120s

- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/ames-6/ignite-cli', '.' ]
  dir: 'IgniteCLI/Ignite-CLI/bin/Release/netcoreapp2.0/publish'

images: ['gcr.io/ames-6/ignite-cli']