steps:
- id: 'Download Nuget API Key'
  name: 'gcr.io/cloud-builders/gsutil'
  args: ['cp', 'gs://ignite-cli/ignite-cli-nuget-key.txt', '.']
  #args: ['kms', 'decrypt', '--ciphertext-file=nuget.txt.enc', '--plaintext-file=nuget.txt', '--location=global', '--keyring=ignite-cli', '--key=ignite-cli']
  #dir: '.'

- id: 'Display Nuget API Key'
  name: 'ubuntu'
  args: ['cat', 'ignite-cli-nuget-key.txt']

- id: 'Build Solution'
  name: 'gcr.io/cloud-builders/dotnet'
  args: ['build', '-c', 'Release']
  dir: './IgniteCLI'

- id: 'Push Nuget Package'
  name: 'gcr.io/cloud-builders/dotnet'
  args: ['nuget', 'push', 'IgniteCLI.1.0.1.nupkg', '-k', '$$APIKEY', '-s', 'https://api.nuget.org/v3/index.json']
  dir: './IgniteCLI/Ignite-CLI/bin/Release'
  secretEnv: ['APIKEY']

secrets:
- kmsKeyName: projects/ames-6/locations/global/keyRings/ignite-cli/cryptoKeys/ignite-cli
  secretEnv:
    APIKEY: 'CiQAbWRKvq56dYFsCB2heVTGl1NcnLzKHcTDQGziYMtvV8MFi+0SWADKLie3QwjAyveFeYpuj7EIqMkEqfV5OFsIkdY8mM8GgVdog6481R2XDrt+hXiYSVnYyInvyfwfFWiFwBBhWufjZrBnfbtBUJMjsjGBgHEf7cE0089O+88='