steps:
- id: 'Download Nuget API Key'
  name: 'gcr.io/cloud-builders/gsutil'
  args: ['cp', 'gs://ignite-cli/ignite-cli-nuget-key.txt', '.']
  #args: ['kms', 'decrypt', '--ciphertext-file=nuget.txt.enc', '--plaintext-file=nuget.txt', '--location=global', '--keyring=ignite-cli', '--key=ignite-cli']
  #dir: '.'

- id: 'Display Nuget API Key'
  name: 'gcr.io/cloud-builders/docker'
  args: ['cat', 'ignite-cli-nuget-key.txt']

- id: 'Build Solution'
  name: 'gcr.io/cloud-builders/dotnet'
  args: ['build', '-c', 'Release']
  dir: './IgniteCLI'

- id: 'Push Nuget Package'
  name: 'gcr.io/cloud-builders/dotnet'
  args: ['nuget', 'push', 'IgniteCLI.1.0.1.nupkg', '-k', '$(./ignite-cli/ignite-cli-nuget-key.txt)', '-s', 'https://api.nuget.org/v3/index.json']
  dir: './IgniteCLI/Ignite-CLI/bin/Release'

# artifacts:
#   objects:
#     location: ['gs://ignite-cli']
#     paths: [IgniteCLI/Ignite-CLI/bin/Release/netcoreapp2.0/publish']