steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - kms
  - decrypt
  - --ciphertext-file=nuget.txt.enc
  - --plaintext-file=nuget.txt
  - --location=global
  - --keyring=ignite-cli
  - --key=ignite-cli

- name: 'gcr.io/cloud-builders/dotnet'
  args: ['publish', '-c', 'Release']
  dir: './IgniteCLI'
  timeout: 120s

- name: 'gcr.io/cloud-builders/dotnet'
  args: ['nuget', 'push', 'IgniteCLI.1.0.1.nupkg', '-k', '$(nuget.txt)', '-s', 'https://api.nuget.org/v3/index.json']

artifacts:
  objects:
    location: ['gs://ignite-cli']
    paths: [IgniteCLI/Ignite-CLI/bin/Release/netcoreapp2.0/publish']